server:
  port: 8083

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2.com:7002/eureka/
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  #之所以使用 ribbon 是因为 Open Feign 本身自带 ribbon
  ReadTimeout: 1000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 1000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
