server:
  port: 8084

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/

feign:
  hystrix:
    enabled: true